name: vm
description: VM specific Dart code and helper scripts
# This package is not intended for consumption on pub.dev. DO NOT publish.
publish_to: none

environment:
  sdk: '>=2.15.0 <3.0.0'

dependencies:
  args: any
  build_integration: any
  collection: any
  crypto: any
  front_end: any
  kernel: any
  package_config: any

dev_dependencies:
  expect: any
  json_rpc_2: any
  path: any
  test: any
  web_socket_channel: any
