name: dartdev

# This package is not intended for consumption on pub.dev. DO NOT publish.
publish_to: none

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  analysis_server: any
  analysis_server_client: any
  analyzer: any
  args: any
  cli_util: any
  collection: any
  dart2native: any
  dart_style: any
  dartdoc: any
  dds: any
  front_end: any
  meta: any
  nnbd_migration: any
  path: any
  pub: any
  telemetry: any
  usage: any

dev_dependencies:
  expect: any
  lints: any
  pub_semver: any
  test: any
  yaml: any
