name: linter
version: 0.0.1
author: Dart Team <misc@dartlang.org>
description: Style linter for Dart.
homepage: https://github.com/dart-lang/linter
dependencies:
  analyzer: '0.24.0-dev.1'
  cli_util: '>=0.0.1 <0.1.0'
dev_dependencies:
  markdown: '>=0.7.1+2 <0.8.0'
  unittest: '>=0.11.0 <0.12.0'