name: linter
version: 0.1.101

author: Dart Team <misc@dartlang.org>

description: >-
  The implementation of the lint rules supported by the analyzer framework.
  This package is not intended to be used directly.
homepage: https://github.com/dart-lang/linter
repository: https://github.com/dart-lang/linter
documentation: https://dart-lang.github.io/linter/lints

environment:
  sdk: '>=2.2.2 <3.0.0'

dependencies:
  analyzer: ^0.39.0
  args: '>=1.4.0 <2.0.0'
  glob: ^1.0.3
  meta: ^1.0.2
  source_span: ^1.0.2
  yaml: ^2.1.2

dev_dependencies:
  cli_util: ^0.1.2
  # Update when 1.3.3 lands.
  # https://github.com/dart-lang/dart_style/issues/866
  dart_style:
    git:
      url: git://github.com/dart-lang/dart_style.git
      ref: 108a94c8b1797d4f535edff2746bf31b185d04b2
  github: ^5.0.0
  grinder: ^0.8.0
  http: ^0.12.0
  markdown: ^2.0.0
  matcher: ^0.12.0
  path: ^1.2.0
  pedantic: ^1.6.0
  pub_semver: ^1.4.2
  test: ^1.9.3
