name: dart2js_info
version: 0.0.1
description: >
  Libraries and tools to process data produced when running dart2js with
  --dump-info.
author: Dart Team <misc@dartlang.org>
homepage: http://dart-lang.github.io/dart2js_info/doc/api/

dependencies:
  path: ^1.3.6
  args: ^0.13.2
  shelf: ^0.6.1+2
  yaml: ^2.1.0

environment:
  sdk: '>=1.11.0 <2.0.0'

dev_dependencies:
  test: ^0.12.3+4
