name: analysis_server_client
version: 2.0.0-dev
description:
  A client wrapper over analysis_server.
  Instances of the class [Server] manage a connection to a server process,
  and facilitate communication to and from the server.
repository: https://github.com/dart-lang/sdk/tree/main/pkg/analysis_server_client

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  path: ^1.8.0
  pub_semver: ^2.0.0

# We use 'any' version constraints here as we get our package versions from
# the dart-lang/sdk repo's DEPS file. Note that this is a special case; the
# best practice for packages is to specify their compatible version ranges.
# See also https://dart.dev/tools/pub/dependencies.
dev_dependencies:
  analyzer: any
  analysis_server: any
  analyzer_utilities: any
  test: any
