include: package:lints/core.yaml

analyzer:
  language:
    strict-casts: true

linter:
  rules:
    avoid_bool_literals_in_conditional_expressions: true
    avoid_unused_constructor_parameters: true
    cancel_subscriptions: true
    comment_references: true
    directives_ordering: true
    omit_local_variable_types: true
    package_api_docs: true
    prefer_const_constructors: true
    throw_in_finally: true
    unnecessary_lambdas: true
    unnecessary_parenthesis: true
    unnecessary_statements: true

    # Disabled due to existing violations.
    non_constant_identifier_names: false
    only_throw_errors: false
    prefer_single_quotes: false
