name: native_assets_builder
version: 0.0.1

# This package is not intended for consumption on pub.dev. DO NOT publish.
publish_to: none

environment:
  sdk: ">=2.17.0 <3.0.0"

# Use 'any' constraints here; we get our versions from the DEPS file.
dependencies:
  kernel: any # For Graph topological sort.
  logging: any
  native_assets_cli: any
  package_config: any

# Use 'any' constraints here; we get our versions from the DEPS file.
dev_dependencies:
  lints: any
  test: any
  yaml: any
