name: dart2js_info
publish_to: none

description: >-
  Libraries and tools to process data produced when running dart2js with
  --dump-info.

environment:
  sdk: '>=2.11.99 <3.0.0'

dependencies:
  args: any
  collection: any
  fixnum: any
  path: any
  protobuf: any
  shelf: any
  yaml: any

dev_dependencies:
  lints: any
  test: any

executables:
  dart2js_info: tools
