include: package:lints/recommended.yaml

analyzer:
  language:
    strict-casts: true
  exclude:
    - test/mock_packages/**
  errors:
    # Increase the severity of the unused_import hint.
    unused_import: warning

    # Lints from the recommended set that conflict w/ analyzer style or will
    # require some work to reach compliance.
    # See: https://github.com/dart-lang/sdk/issues/48785
    avoid_renaming_method_parameters: ignore
    camel_case_types: ignore
    constant_identifier_names: ignore
    file_names: ignore
    hash_and_equals: ignore
    implementation_imports: ignore
    library_private_types_in_public_api: ignore
    non_constant_identifier_names: ignore
    overridden_fields: ignore
    prefer_function_declarations_over_variables: ignore
    # todo: add ignore to `protocol_generated.dart`
    prefer_interpolation_to_compose_strings: ignore
    prefer_void_to_null: ignore
    provide_deprecation_message: ignore

linter:
  rules:
    - depend_on_referenced_packages
    - unnecessary_parenthesis
