include: package:lints/recommended.yaml

analyzer:
  language:
    strict-casts: true
  exclude:
    - test/mock_packages/**
  errors:
    # Increase the severity of the unused_import hint.
    unused_import: warning

    # Lints from the recommended set that conflict w/ analyzer style or will
    # require some work to reach compliance.
    # See: https://github.com/dart-lang/sdk/issues/48785
    camel_case_types: ignore
    constant_identifier_names: ignore
    file_names: ignore
    implementation_imports: ignore
    non_constant_identifier_names: ignore
    overridden_fields: ignore
    prefer_void_to_null: ignore
    provide_deprecation_message: ignore

linter:
  rules:
    - depend_on_referenced_packages
    - unawaited_futures
    - unnecessary_parenthesis
    - use_super_parameters
