# This pubspec is currently mainly used to make it easier to develop on dart2js
# by making it a standalone package.
name: compiler
# This package is not intended for consumption on pub.dev. DO NOT publish.
publish_to: none
environment:
  sdk: '>=2.16.0 <3.0.0'

# NOTE: `pub get / pub upgrade` are generally not needed when working on this
# package. The `.packages` file in the repository root will be used by default.
dependencies:
  _fe_analyzer_shared: any
  _js_interop_checks: any
  collection: any
  crypto: any
  dart2js_info: any
  front_end: any
  js_ast: any
  js_runtime: any
  kernel: any

dev_dependencies:
  args: any
  dart_style: any
  http: any
  js: any
  path: any
  source_maps: any
  async_helper: any
  dart2js_tools: any
  expect: any
  modular_test: any
  sourcemap_testing: any
  testing: any
