# Helper package for testing sourcemaps. Used by ddc and dart2js.
name: sourcemap_testing
# This package is not intended for consumption on pub.dev. DO NOT publish.
publish_to: none

environment:
  sdk: '>=2.11.0 <3.0.0'

dependencies:
  _fe_analyzer_shared: any
  dart2js_tools: any
  expect: any
  path: any
  source_maps: any
  source_span: any

dev_dependencies:
  lints: any
