include: package:lints/recommended.yaml

analyzer:
  errors:
    # There are currently 175 violations.
    always_declare_return_types: ignore
    # There are currently 60 violations.
    annotate_overrides: ignore
    # A number of class names mix UpperCamelCase with underscores.
    camel_case_types: ignore
    # This package freely and frequently imports implementation from analyzer.
    implementation_imports: ignore
    # Our test methods are named with snake_case.
    non_constant_identifier_names: ignore
    # There are currently 200 violations.
    omit_local_variable_types: ignore
    # There are currently 20 violations.
    unawaited_futures: ignore

  language:
    strict-casts: true

linter:
  rules:
    - await_only_futures
    - empty_constructor_bodies
    - empty_statements
    - unnecessary_brace_in_string_interps
    - valid_regexps
