name: nnbd_migration

# This package is not intended for consumption on pub.dev. DO NOT publish.
publish_to: none

environment:
  sdk: '>=2.14.0 <3.0.0'

dependencies:
  _fe_analyzer_shared: any
  analyzer: any
  analyzer_plugin: any
  args: any
  cli_util: any
  collection: any
  crypto: any
  meta: any
  path: any
  pub_semver: any
  source_span: any
  yaml: any

dev_dependencies:
  analyzer_utilities: any
  http: any
  lints: any
  test: any
  test_reflective_loader: any
