name: xref_extractor
description: A sample command-line application.
# This package is not intended for consumption on pub.dev. DO NOT publish.
publish_to: none

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  path: any

dev_dependencies:
  lints: any
