name: status_file
# This package is not intended for consumption on pub.dev. DO NOT publish.
publish_to: none

environment:
  sdk: "^2.12.0"

dependencies:
  path: any
  args: any

dev_dependencies:
  expect: any
