name: frontend_server
description: A resident kernel compiler
# This package is not intended for consumption on pub.dev. DO NOT publish.
publish_to: none

environment:
  sdk: "^2.15.0"

dependencies:
  _fe_analyzer_shared: any
  args: any
  build_integration: any
  compiler: any
  dev_compiler: any
  front_end: any
  kernel: any
  package_config: any
  path: any
  usage: any
  vm: any

dev_dependencies:
  mockito: any
  test: any
